"""Fix access_token

Revision ID: fe7eb32be2e5
Revises: b04e3f3aa4ac
Create Date: 2023-05-05 12:13:50.568899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7eb32be2e5'
down_revision = 'b04e3f3aa4ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesstoken', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accesstoken', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accesstoken', type_='foreignkey')
    op.drop_column('accesstoken', 'user_id')
    # ### end Alembic commands ###
