"""Добавлены категории для инцидентов

Revision ID: a6f7efae30e6
Revises: 7c74aeb88c98
Create Date: 2023-04-15 10:07:37.961635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f7efae30e6'
down_revision = '7c74aeb88c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'category')
    # ### end Alembic commands ###
