"""Fix created_at

Revision ID: 260bbf04d79d
Revises: a6f7efae30e6
Create Date: 2023-04-27 10:32:42.060190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260bbf04d79d'
down_revision = 'a6f7efae30e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
